[toolchain]
anchor_version = "0.30.1"
solana_version = "1.18.26"

[features]
resolution = true
skip-lint = false

[programs.devnet]
trustchain_lite = "3AJ7pp8SVW91iFYhB5LgctFrsgaeGKVX3qRVsN48922M"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[workspace]
members = [
  "programs/*"
]

